Mohana
manipalroboticssg/Website pull request #11
Opened 2022-12-16 17:28 UTC by mohanamisra

### Changes:

1) Added CSS to Header, 'Highlights and Blogs', 'Events and Workshops' and Footer.
2) Added the Image Carousel
3) Modified the base HTML as necessary
4) Updated the index.js file for slideshow functionality

2022-12-19 06:11 UTC, CH13F-1419 commented
The elements of the event blocks don't seem to scale to 150% zoom, they seem to be scaled to 12% instead. Try to make it so that it works at 150% zoom, since most websites are actually rated for 150% zoom.
![Refer to this screenshot.](https://user-images.githubusercontent.com/63255148/208359306-95a65bed-fea8-449f-838e-708e710195c3.png)

2022-12-19 06:13 UTC, CH13F-1419 commented
The footer doesn't have the appropriate edge padding as the other elements, since it's hugging the edge of the screen way too much.

![Footer](https://user-images.githubusercontent.com/63255148/208359747-a9274f25-770d-4ac4-ba64-262a4fe2c7e3.png)

2022-12-19 06:54 UTC, CH13F-1419 requested changes
Most of the changes are cosmetic in nature but the faster we resolve this the easier it will be down the line. Once you do these changes then there's not much to do for the home page.

Also, maybe it's just my computer, but the carousel wasn't moving, I guess you need to edit the carousel timing.

2022-12-19 06:54 UTC, CH13F-1419 commented on index.css
> +  /* Next & previous buttons */
Increase the size of the arrows a litle bit so that it's easy to click on.

2022-12-19 06:54 UTC, CH13F-1419 commented on index.css
> +/* EVENTS SECTION STARTS */
You'll have to try making it so that the event blocks are in grid form at 150% zoom. It works at 125%, but putting it to 150% makes it convert to vertical columns.

2022-12-19 06:54 UTC, CH13F-1419 commented on index.css
>      padding-top: 1px;
You'll have to add some left-right padding here.

2022-12-19 06:54 UTC, CH13F-1419 commented on index.css
>  .buttons {
The button padding doesn't cover the whole yellow block. The width seems fine but you'll have to increase the height.

2022-12-19 06:54 UTC, CH13F-1419 commented on index.html
>                      <a href="">Sitemap &nbsp;&nbsp;&nbsp;</a>
See how you can make a sitemap for the website. It basically just shows a nested list of links that exist on the entire website. You can make it manually but do see if there's any automated methods.

2022-12-19 07:09 UTC, mohanamisra commented
The carousel moves manually.

Should I change it to an automatic slideshow then?

On Mon, 19 Dec 2022, 12:24 Neehal Sharrma, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Most of the changes are cosmetic in nature but the faster we resolve this
> the easier it will be down the line. Once you do these changes then there's
> not much to do for the home page.
>
> Also, maybe it's just my computer, but the carousel wasn't moving, I guess
> you need to edit the carousel timing.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051845604>
> :
>
> > -    object-fit: contain;
> -}
> -/* forward & Back buttons */
> -.Back,
> -.forward {
> +    margin-top: -20px;
> +    max-height: 400px;
> +    overflow: hidden;
> +  }
> +
> +  /* Hide the images by default */
> +  .mySlides {
> +    display: none;
> +  }
> +
> +  /* Next & previous buttons */
>
> Increase the size of the arrows a litle bit so that it's easy to click on.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051847295>
> :
>
> > +    font-family: 'Montserrat', sans-serif;
> +    font-weight: 600;
> +    font-size: 25px;
> +    text-align: center;
> +}
> +
> +.blog-snippet{
> +    font-size: 20px;
> +    font-family: sans-serif;
> +    text-align: center;
> +}
> +
> +/* BLOG SECTION ENDS */
> +
> +
> +/* EVENTS SECTION STARTS */
>
> You'll have to try making it so that the event blocks are in grid form at
> 150% zoom. It works at 125%, but putting it to 150% makes it convert to
> vertical columns.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051847930>
> :
>
> >  .footer {
>      background: #1f3d2f;
>      color: mintcream;
> -    bottom: 0%;
> -    height: 230px;
> -    margin-top: 25px;
>      padding-top: 1px;
>
> You'll have to add some left-right padding here.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051851146>
> :
>
> >  }
> +
>  .buttons {
>
> The button padding doesn't cover the whole yellow block. The width seems
> fine but you'll have to increase the height.
> ------------------------------
>
> In index.html
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051852178>
> :
>
> >                  <p><img src="./image/MRSG-logo-horizontal-whitetxt.png" alt="MRSG" width=30% height=10% class="mid">
> -                    &nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
> +                     &nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
>                      <a href="#top">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; Back To Top &nbsp;&nbsp;&nbsp;</a>
>                      <a href="./index.html">Home &nbsp;&nbsp;&nbsp;</a>
>                      <a href="">Sitemap &nbsp;&nbsp;&nbsp;</a>
>
> See how you can make a sitemap for the website. It basically just shows a
> nested list of links that exist on the entire website. You can make it
> manually but do see if there's any automated methods.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/manipalroboticssg/Website/pull/11#pullrequestreview-1222351660>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVX24M7KWN3LW2LW2R5PZUDWOABBNANCNFSM6AAAAAATBIU5X4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-19 07:10 UTC, mohanamisra commented
I'll get on this!

On Mon, 19 Dec 2022, 12:24 Neehal Sharrma, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Most of the changes are cosmetic in nature but the faster we resolve this
> the easier it will be down the line. Once you do these changes then there's
> not much to do for the home page.
>
> Also, maybe it's just my computer, but the carousel wasn't moving, I guess
> you need to edit the carousel timing.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051845604>
> :
>
> > -    object-fit: contain;
> -}
> -/* forward & Back buttons */
> -.Back,
> -.forward {
> +    margin-top: -20px;
> +    max-height: 400px;
> +    overflow: hidden;
> +  }
> +
> +  /* Hide the images by default */
> +  .mySlides {
> +    display: none;
> +  }
> +
> +  /* Next & previous buttons */
>
> Increase the size of the arrows a litle bit so that it's easy to click on.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051847295>
> :
>
> > +    font-family: 'Montserrat', sans-serif;
> +    font-weight: 600;
> +    font-size: 25px;
> +    text-align: center;
> +}
> +
> +.blog-snippet{
> +    font-size: 20px;
> +    font-family: sans-serif;
> +    text-align: center;
> +}
> +
> +/* BLOG SECTION ENDS */
> +
> +
> +/* EVENTS SECTION STARTS */
>
> You'll have to try making it so that the event blocks are in grid form at
> 150% zoom. It works at 125%, but putting it to 150% makes it convert to
> vertical columns.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051847930>
> :
>
> >  .footer {
>      background: #1f3d2f;
>      color: mintcream;
> -    bottom: 0%;
> -    height: 230px;
> -    margin-top: 25px;
>      padding-top: 1px;
>
> You'll have to add some left-right padding here.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051851146>
> :
>
> >  }
> +
>  .buttons {
>
> The button padding doesn't cover the whole yellow block. The width seems
> fine but you'll have to increase the height.
> ------------------------------
>
> In index.html
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1051852178>
> :
>
> >                  <p><img src="./image/MRSG-logo-horizontal-whitetxt.png" alt="MRSG" width=30% height=10% class="mid">
> -                    &nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
> +                     &nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
>                      <a href="#top">&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; Back To Top &nbsp;&nbsp;&nbsp;</a>
>                      <a href="./index.html">Home &nbsp;&nbsp;&nbsp;</a>
>                      <a href="">Sitemap &nbsp;&nbsp;&nbsp;</a>
>
> See how you can make a sitemap for the website. It basically just shows a
> nested list of links that exist on the entire website. You can make it
> manually but do see if there's any automated methods.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/manipalroboticssg/Website/pull/11#pullrequestreview-1222351660>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVX24M7KWN3LW2LW2R5PZUDWOABBNANCNFSM6AAAAAATBIU5X4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-19 07:12 UTC, CH13F-1419 commented
> The carousel moves manually. Should I change it to an automatic slideshow then?

Oh yea I'm aware it's moveable I though it's automatic XD yeah it's better if you make it automatic, make it change every 3-5 seconds, whichever looks right.

2022-12-26 06:09 UTC, CH13F-1419 requested changes
A lot of issues have been stamped out since the last review, great! There's just a couple nitpicky things I'd want change and then we can approve this PR.

I don't think I noticed this before during the last review, but on zooming out the blog row tends to squash itself in an attempt to stretch to fit the page width. See if you can lock the row similar to what you did to the event card grid.

![image](https://user-images.githubusercontent.com/63255148/209509665-589a2d68-58aa-47c1-8cb6-260ba30ef6b5.png)

There's similar behaviour on both Chrome and Edge, so these suggestions should technically be browser-agnostic. In any case you can connect the folder you're working in with the browser inspect element debugger to get more information about what element you're looking at and also try to experiment that way. I've used Edge but I reckon you could do this with Chrome as well.

![image](https://user-images.githubusercontent.com/63255148/209509613-0e265d01-c6a9-40ee-9560-495acbefa2c3.png)

Aside from the specific comments I think that's about it. There do seem to be some other things but I guess that's just me being too fussy about it. I'll take a look at those myself later on.

2022-12-26 06:12 UTC, CH13F-1419 commented on index.html
>                      <a href="">Sitemap &nbsp;&nbsp;&nbsp;</a>
This will be put off till later as discussed.

2022-12-26 06:58 UTC, mohanamisra commented
I'll work on the register buttons again today. ✌🏻

The thing with the blogs is that I used flex, so it built-in responsiveness
(so if the page increases or decreases in width for different devices, the
blog cards appear more or less in the same line and same arrangement).

But I had to hard-code the width values of event cards for now, because
their responsiveness was making them appear in one line like you pointed
out before. If I use CSS grid then maybe I can make that responsive too, to
prevent the event cards from looking tiny on zoomed out pages.


Should I then remove the responsive characters of the blog cards or let it
be for now? 😅

On Mon, 26 Dec 2022, 11:39 Neehal Sharrma, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> A lot of issues have been stamped out since the last review, great!
> There's just a couple nitpicky things I'd want change and then we can
> approve this PR.
>
> I don't think I noticed this before during the last review, but on zooming
> out the blog row tends to squash itself in an attempt to stretch to fit the
> page width. See if you can lock the row similar to what you did to the
> event card grid.
>
> [image: image]
> <https://user-images.githubusercontent.com/63255148/209509665-589a2d68-58aa-47c1-8cb6-260ba30ef6b5.png>
>
> There's similar behaviour on both Chrome and Edge, so these suggestions
> should technically be browser-agnostic. In any case you can connect the
> folder you're working in with the browser inspect element debugger to get
> more information about what element you're looking at and also try to
> experiment that way. I've used Edge but I reckon you could do this with
> Chrome as well.
>
> [image: image]
> <https://user-images.githubusercontent.com/63255148/209509613-0e265d01-c6a9-40ee-9560-495acbefa2c3.png>
>
> Aside from the specific comments I think that's about it. There do seem to
> be some other things but I guess that's just me being too fussy about it.
> I'll take a look at those myself later on.
> ------------------------------
>
> In index.css
> <https://github.com/manipalroboticssg/Website/pull/11#discussion_r1057080022>
> :
>
> >  /* EVENTS SECTION ENDS */
>
>  .footer {
>      background: #1f3d2f;
>      color: mintcream;
> -    padding-top: 1px;
> +    padding: 1px 24px 16px 24px;
>
> You'll have to modify this a tad bit more. The padding still doesn't cover
> the whole block. Check the below image. There seems to be two elements on
> top of each other, one simple button one and one with the link thing. I
> don't seem to see this in the "Read More" buttons, maybe try experiementing
> with those as well.
>
> [image: image]
> <https://user-images.githubusercontent.com/63255148/209508824-637253bd-f60c-4d75-91a2-27d120d861dc.png>
>
> [image: image]
> <https://user-images.githubusercontent.com/63255148/209508924-21527893-8447-4ba5-9c21-8af8ffcc53cb.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/manipalroboticssg/Website/pull/11#pullrequestreview-1229876431>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVX24M733FVNBP4FOPHAHXDWPEZA7ANCNFSM6AAAAAATBIU5X4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-26 07:04 UTC, CH13F-1419 commented
> I'll work on the register buttons again today. ✌🏻 The thing with the blogs is that I used flex, so it built-in responsiveness (so if the page increases or decreases in width for different devices, the blog cards appear more or less in the same line and same arrangement). But I had to hard-code the width values of event cards for now, because their responsiveness was making them appear in one line like you pointed out before. If I use CSS grid then maybe I can make that responsive too, to prevent the event cards from looking tiny on zoomed out pages. Should I then remove the responsive characters of the blog cards or let it be for now? 😅

Oh is that so, hmm then I guess remove the responsive thing, I have something is mind but for now we'll just move with a hardcoded UI element for this.

The website looks perfect at 125% zoom, so for the time being we'll move with this only.

2022-12-26 07:05 UTC, CH13F-1419 commented
Also, when pushing changes once you are done with any requested change, do click the "Resolve Conversation" button (if a conversation exists referencing that change) so that I'm notified that this has been done.

![image](https://user-images.githubusercontent.com/63255148/209515771-b371cc7e-22d9-4fec-adcb-f3c3566257e1.png)

2022-12-27 05:11 UTC, CH13F-1419 approved these changes
Yup everything looks good! We'll work with this version for now.

2022-12-27 05:23 UTC, merged

2022-12-27 06:17 UTC, mohanamisra commented
> Yup everything looks good! We'll work with this version for now.

Awesome! 👍😄